### ISSUE TITLE
Add user output to results.json

### ISSUE THREAD

**Issue by bkhl** [exercism/bash-test-runner#2]
Add output information to `results.json`, as per: https://github.com/exercism/automated-tests/pull/34

**Comment by bkhl** [comment]
As per https://github.com/exercism/automated-tests/pull/41, user output should be added to output for all tests, including successful tests.

**Comment by glennj** [comment]
Because we use the bats `run` command for (almost) all tests, anything the user prints to stdout or stderr will be captured. I don't think there's any way to pull out "debug output" from the "program output".

Now that we're using `assert_output`, all the actual output will be shown to the user when the test fails.
<img width="1391" alt="assert_output" src="https://user-images.githubusercontent.com/122470/135137102-0a676633-3867-48a7-8a76-3bb9e8d07fd0.png">
